/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;
import javax.swing.*;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author brand
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    DefaultListModel dm = new DefaultListModel();
    DefaultListModel TotalOrder = new DefaultListModel();
    
    public void addToList(String name){
        dm.addElement(name);
        CartList.setModel(dm);
        
//        try{
//        //create a statement object
//            Statement stmt = conn.createStatement();
//            //create an SQL statement
//            try{
//                String sqlStatement = "SELECT * FROM public.\"Customers\" WHERE \"CustomerID\" = " + ID;
//                //send statement to DBMS
//                ResultSet result = stmt.executeQuery(sqlStatement);
//                result.next();
//                String dbfName = result.getString("FirstName");
//                String dblName = result.getString("LastName");
//                String dbID = result.getString("CustomerID");
//                
//                if(fName.toLowerCase().equals(dbfName.toLowerCase()) && lName.toLowerCase().equals(dblName.toLowerCase())
//                        && ID.equals(dbID)){
//                    dispose();
//                    NewJFrame f = new NewJFrame();
//                    f.setVisible(true);
//                } else{
//                    JOptionPane.showMessageDialog(null, "Incorrect Data");
//                }                
//            } catch(Exception e){
//                JOptionPane.showMessageDialog(null, "Invalid Login");
//            }
//        } catch (Exception e){
//            JOptionPane.showMessageDialog(null,"Error accessing Database.");
//        }
        //TotalOrder.add(ID);
    }
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        KPcombo = new javax.swing.JButton();
        PizzaCombo = new javax.swing.JButton();
        DKPcombo = new javax.swing.JButton();
        DognChips = new javax.swing.JButton();
        TKPcombo = new javax.swing.JButton();
        SupremeKombo = new javax.swing.JButton();
        SailorsSuprise = new javax.swing.JButton();
        CaptainSpecial = new javax.swing.JButton();
        JPCombo = new javax.swing.JButton();
        PipMeal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CartList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        ClearCart = new javax.swing.JButton();
        SubmitOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        KPcombo.setText("Krabby Patty Combo");
        KPcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KPcomboActionPerformed(evt);
            }
        });

        PizzaCombo.setText("Krusty Krab Pizza");
        PizzaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaComboActionPerformed(evt);
            }
        });

        DKPcombo.setText("Double Krabby Patty Combo");
        DKPcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DKPcomboActionPerformed(evt);
            }
        });

        DognChips.setText("Salty Sea Dog n' Chips");
        DognChips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DognChipsActionPerformed(evt);
            }
        });

        TKPcombo.setText("Triple Krabby Patty Combo");
        TKPcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKPcomboActionPerformed(evt);
            }
        });

        SupremeKombo.setText("Supreme Krusty Kombo");
        SupremeKombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupremeKomboActionPerformed(evt);
            }
        });

        SailorsSuprise.setText("Sailors' Suprise");
        SailorsSuprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SailorsSupriseActionPerformed(evt);
            }
        });

        CaptainSpecial.setText("Captain's Special");
        CaptainSpecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaptainSpecialActionPerformed(evt);
            }
        });

        JPCombo.setText("Jelly Patty Combo");
        JPCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPComboActionPerformed(evt);
            }
        });

        PipMeal.setText("Pipsqueak Meal");
        PipMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PipMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DognChips)
                        .addGap(52, 52, 52)
                        .addComponent(SupremeKombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(KPcombo)
                        .addGap(29, 29, 29)
                        .addComponent(DKPcombo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TKPcombo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SailorsSuprise, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PizzaCombo)
                    .addComponent(CaptainSpecial))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(JPCombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PipMeal)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PizzaCombo)
                    .addComponent(KPcombo)
                    .addComponent(DKPcombo)
                    .addComponent(TKPcombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DognChips)
                    .addComponent(SupremeKombo)
                    .addComponent(SailorsSuprise)
                    .addComponent(CaptainSpecial))
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPCombo)
                    .addComponent(PipMeal))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Combos", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Entrees", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sides", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Drinks", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Desserts", jPanel5);

        jScrollPane1.setViewportView(CartList);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel1.setText("Cart");

        ClearCart.setText("Clear");
        ClearCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearCartActionPerformed(evt);
            }
        });

        SubmitOrder.setText("Submit Order");
        SubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClearCart, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SubmitOrder)))))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearCart)
                    .addComponent(SubmitOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        FirstForm f = new FirstForm();
        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void KPcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KPcomboActionPerformed
        // TODO add your handling code here:
        addToList(KPcombo.getText());
        
    }//GEN-LAST:event_KPcomboActionPerformed

    private void PizzaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaComboActionPerformed
        // TODO add your handling code here:
        addToList(PizzaCombo.getText());
    }//GEN-LAST:event_PizzaComboActionPerformed

    private void DKPcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DKPcomboActionPerformed
        // TODO add your handling code here:
        addToList(DKPcombo.getText());
    }//GEN-LAST:event_DKPcomboActionPerformed

    private void DognChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DognChipsActionPerformed
        // TODO add your handling code here:
        addToList(DognChips.getText());
    }//GEN-LAST:event_DognChipsActionPerformed

    private void TKPcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKPcomboActionPerformed
        // TODO add your handling code here:
        addToList(TKPcombo.getText());
    }//GEN-LAST:event_TKPcomboActionPerformed

    private void SupremeKomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupremeKomboActionPerformed
        // TODO add your handling code here:
        addToList(SupremeKombo.getText());
    }//GEN-LAST:event_SupremeKomboActionPerformed

    private void SailorsSupriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SailorsSupriseActionPerformed
        // TODO add your handling code here:
        addToList(SailorsSuprise.getText());
    }//GEN-LAST:event_SailorsSupriseActionPerformed

    private void CaptainSpecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaptainSpecialActionPerformed
        // TODO add your handling code here:
        addToList(CaptainSpecial.getText());
    }//GEN-LAST:event_CaptainSpecialActionPerformed

    private void JPComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPComboActionPerformed
        // TODO add your handling code here:
        addToList(JPCombo.getText());
    }//GEN-LAST:event_JPComboActionPerformed

    private void PipMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PipMealActionPerformed
        // TODO add your handling code here:
        addToList(PipMeal.getText());
    }//GEN-LAST:event_PipMealActionPerformed

    private void ClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearCartActionPerformed
        // TODO add your handling code here:
        dm.clear();
        CartList.setModel(dm);
    }//GEN-LAST:event_ClearCartActionPerformed

    private void SubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitOrderActionPerformed
        
    }//GEN-LAST:event_SubmitOrderActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaptainSpecial;
    private javax.swing.JList<String> CartList;
    private javax.swing.JButton ClearCart;
    private javax.swing.JButton DKPcombo;
    private javax.swing.JButton DognChips;
    private javax.swing.JButton JPCombo;
    private javax.swing.JButton KPcombo;
    private javax.swing.JButton PipMeal;
    private javax.swing.JButton PizzaCombo;
    private javax.swing.JButton SailorsSuprise;
    private javax.swing.JButton SubmitOrder;
    private javax.swing.JButton SupremeKombo;
    private javax.swing.JButton TKPcombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
