/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// temp comment

package mypackage;
import javax.swing.*;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author brand
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    DBSearch db = new DBSearch();
    DefaultListModel dm = new DefaultListModel(); //Krabby patty, krusty pizza
    DefaultListModel TotalOrder = new DefaultListModel(); //E1. E2
    DefaultListModel<String> ItemList = new DefaultListModel();
    DefaultListModel<String> PriceList = new DefaultListModel();
    int currentFirstItem = 0;
    
    public void addToList(String name){
        dm.addElement(name);
        
        CartList.setModel(dm);
    }
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        BackBTN = new javax.swing.JButton();
        MenuTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Menu1BTN = new javax.swing.JButton();
        Menu4BTN = new javax.swing.JButton();
        Menu2BTN = new javax.swing.JButton();
        Menu5BTN = new javax.swing.JButton();
        Menu3BTN = new javax.swing.JButton();
        Menu6BTN = new javax.swing.JButton();
        Menu7BTN = new javax.swing.JButton();
        Menu8BTN = new javax.swing.JButton();
        ComboListBTN = new javax.swing.JButton();
        EntreeListBTN = new javax.swing.JButton();
        SidesListBTN = new javax.swing.JButton();
        DrinkListBTN = new javax.swing.JButton();
        DessertListBTN = new javax.swing.JButton();
        NextPageBTN = new javax.swing.JButton();
        PrevPageBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CartList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        ClearCart = new javax.swing.JButton();
        SubmitOrder = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackBTN.setText("Login");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        Menu1BTN.setText("1");
        Menu1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1BTNActionPerformed(evt);
            }
        });

        Menu4BTN.setText("4");
        Menu4BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu4BTNActionPerformed(evt);
            }
        });

        Menu2BTN.setText("2");
        Menu2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2BTNActionPerformed(evt);
            }
        });

        Menu5BTN.setText("5");
        Menu5BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu5BTNActionPerformed(evt);
            }
        });

        Menu3BTN.setText("3");
        Menu3BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu3BTNActionPerformed(evt);
            }
        });

        Menu6BTN.setText("6");
        Menu6BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu6BTNActionPerformed(evt);
            }
        });

        Menu7BTN.setText("7");
        Menu7BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu7BTNActionPerformed(evt);
            }
        });

        Menu8BTN.setText("8");
        Menu8BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu8BTNActionPerformed(evt);
            }
        });

        ComboListBTN.setText("Combos");
        ComboListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboListBTNActionPerformed(evt);
            }
        });

        EntreeListBTN.setText("Entrees");
        EntreeListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreeListBTNActionPerformed(evt);
            }
        });

        SidesListBTN.setText("Sides");
        SidesListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SidesListBTNActionPerformed(evt);
            }
        });

        DrinkListBTN.setText("Drinks");
        DrinkListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkListBTNActionPerformed(evt);
            }
        });

        DessertListBTN.setText("Desserts");
        DessertListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertListBTNActionPerformed(evt);
            }
        });

        NextPageBTN.setText("Next Page");
        NextPageBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextPageBTNActionPerformed(evt);
            }
        });

        PrevPageBTN.setText("Prev Page");
        PrevPageBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevPageBTNActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(PrevPageBTN)
                .addGap(150, 150, 150)
                .addComponent(NextPageBTN)
                .addGap(184, 184, 184))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Menu5BTN)
                            .addComponent(Menu1BTN)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Menu2BTN)
                            .addComponent(Menu6BTN)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Menu3BTN)
                            .addComponent(Menu7BTN)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Menu4BTN)
                            .addComponent(Menu8BTN)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ComboListBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EntreeListBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SidesListBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DrinkListBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DessertListBTN)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboListBTN)
                    .addComponent(EntreeListBTN)
                    .addComponent(SidesListBTN)
                    .addComponent(DrinkListBTN)
                    .addComponent(DessertListBTN))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Menu4BTN)
                    .addComponent(Menu1BTN)
                    .addComponent(Menu2BTN)
                    .addComponent(Menu3BTN))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Menu5BTN)
                    .addComponent(Menu6BTN)
                    .addComponent(Menu7BTN)
                    .addComponent(Menu8BTN))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextPageBTN)
                    .addComponent(PrevPageBTN))
                .addGap(40, 40, 40))
        );

        MenuTab.addTab("Menu", jPanel1);

        jScrollPane1.setViewportView(CartList);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel1.setText("Cart");

        ClearCart.setText("Clear");
        ClearCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearCartActionPerformed(evt);
            }
        });

        SubmitOrder.setText("Submit Order");
        SubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackBTN)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClearCart, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SubmitOrder)))))
                .addGap(18, 18, 18)
                .addComponent(MenuTab, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackBTN)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearCart)
                    .addComponent(SubmitOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuTab, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        dispose();
        FirstForm f = new FirstForm();
        f.setVisible(true);
    }//GEN-LAST:event_BackBTNActionPerformed

    
    private void formatButtons() {
        
        DefaultListModel<javax.swing.JButton> buttonsArray = new DefaultListModel();
        buttonsArray.addElement(Menu1BTN);
        buttonsArray.addElement(Menu2BTN);
        buttonsArray.addElement(Menu3BTN);
        buttonsArray.addElement(Menu4BTN);
        buttonsArray.addElement(Menu5BTN);
        buttonsArray.addElement(Menu6BTN);
        buttonsArray.addElement(Menu7BTN);
        buttonsArray.addElement(Menu8BTN);
        
        DefaultListModel<javax.swing.JLabel> textFieldArray = new DefaultListModel();
        textFieldArray.addElement(jLabel2);
        textFieldArray.addElement(jLabel3);
        textFieldArray.addElement(jLabel4);
        textFieldArray.addElement(jLabel5);
        textFieldArray.addElement(jLabel6);
        textFieldArray.addElement(jLabel7);
        textFieldArray.addElement(jLabel8);
        textFieldArray.addElement(jLabel9);
        
        Integer itemsOnPage = ItemList.size() - currentFirstItem;
        if (itemsOnPage > 8) {
            itemsOnPage = 8;
        }
        if (currentFirstItem + 8 < ItemList.size()) {
            NextPageBTN.setVisible(true);
        } else {
            NextPageBTN.setVisible(false);
        }
        if (currentFirstItem == 0) {
            PrevPageBTN.setVisible(false);
        } else {
            PrevPageBTN.setVisible(true);
        }
        for (int i = 0; i < itemsOnPage; i++) {
            buttonsArray.elementAt(i).setVisible(true);
            buttonsArray.elementAt(i).setText(ItemList.elementAt(currentFirstItem+i));
            textFieldArray.elementAt(i).setVisible(true);
            textFieldArray.elementAt(i).setText(PriceList.elementAt(currentFirstItem+i));
        }
        for (int i = itemsOnPage; i < 8; i++) {
            buttonsArray.elementAt(i).setVisible(false);
            textFieldArray.elementAt(i).setVisible(false);
        }
    }
    
    private void ClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearCartActionPerformed
        // TODO add your handling code here:
        dm.clear();
        CartList.setModel(dm);
    }//GEN-LAST:event_ClearCartActionPerformed

    private void SubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitOrderActionPerformed
        
    }//GEN-LAST:event_SubmitOrderActionPerformed

    private void PrevPageBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevPageBTNActionPerformed
        currentFirstItem -= 8;
        formatButtons();
    }//GEN-LAST:event_PrevPageBTNActionPerformed

    private void NextPageBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextPageBTNActionPerformed
        // TODO add your handling code here:
        currentFirstItem += 8;
        formatButtons();
    }//GEN-LAST:event_NextPageBTNActionPerformed

    private void DessertListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertListBTNActionPerformed
        // TODO add your handling code here:
        ResultSet result = db.query("SELECT * FROM public.\"MenuItems\" WHERE \"ItemID\" LIKE \'D%\'");
        ItemList.clear();
        PriceList.clear();
        currentFirstItem = 0;
        try {
            while(result.next()){
                ItemList.addElement(result.getString("Name"));
                PriceList.addElement("$" + String.valueOf(result.getDouble("Price")));
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Query Error");
        }

        formatButtons();

    }//GEN-LAST:event_DessertListBTNActionPerformed

    private void DrinkListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkListBTNActionPerformed
        // TODO add your handling code here:
        ResultSet result = db.query("SELECT * FROM public.\"MenuItems\" WHERE \"ItemID\" LIKE \'B%\'");
        ItemList.clear();
        PriceList.clear();
        currentFirstItem = 0;
        try {
            while(result.next()){
                ItemList.addElement(result.getString("Name"));
                PriceList.addElement("$" + String.valueOf(result.getDouble("Price")));
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Query Error");
        }

        formatButtons();

    }//GEN-LAST:event_DrinkListBTNActionPerformed

    private void SidesListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SidesListBTNActionPerformed
        // TODO add your handling code here:
        ResultSet result = db.query("SELECT * FROM public.\"MenuItems\" WHERE \"ItemID\" LIKE \'S%\'");
        ItemList.clear();
        PriceList.clear();
        currentFirstItem = 0;
        try {
            while(result.next()){
                ItemList.addElement(result.getString("Name"));
                PriceList.addElement("$" + String.valueOf(result.getDouble("Price")));
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Query Error");
        }

        formatButtons();

    }//GEN-LAST:event_SidesListBTNActionPerformed

    private void EntreeListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreeListBTNActionPerformed
        // TODO add your handling code here:
        ResultSet result = db.query("SELECT * FROM public.\"MenuItems\" WHERE \"ItemID\" LIKE \'E%\'");
        ItemList.clear();
        PriceList.clear();
        currentFirstItem = 0;
        try {
            while(result.next()){
                ItemList.addElement(result.getString("Name"));
                PriceList.addElement("$" + String.valueOf(result.getDouble("Price")));
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Query Error");
        }

        formatButtons();

    }//GEN-LAST:event_EntreeListBTNActionPerformed

    private void ComboListBTNActionPerformed_helper() {
        ResultSet result = db.query("SELECT * FROM public.\"Combos\"");
        ItemList.clear();
        PriceList.clear();
        currentFirstItem = 0;
        try {
            while(result.next()){
                ItemList.addElement(result.getString("Name"));
                PriceList.addElement("$" + String.valueOf(result.getDouble("Price")));
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Query Error");
        }
        formatButtons();
    }
    
    private void ComboListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboListBTNActionPerformed
        ComboListBTNActionPerformed_helper();
    }//GEN-LAST:event_ComboListBTNActionPerformed

    private void Menu8BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu8BTNActionPerformed
        // TODO add your handling code here:
        addToList(Menu8BTN.getText());
    }//GEN-LAST:event_Menu8BTNActionPerformed

    private void Menu7BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu7BTNActionPerformed
        // TODO add your handling code here:
        addToList(Menu7BTN.getText());
    }//GEN-LAST:event_Menu7BTNActionPerformed

    private void Menu6BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu6BTNActionPerformed
        // TODO add your handling code here:
        addToList(Menu6BTN.getText());
    }//GEN-LAST:event_Menu6BTNActionPerformed

    private void Menu3BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu3BTNActionPerformed
        // TODO add your handling code here:
        addToList(Menu3BTN.getText());
    }//GEN-LAST:event_Menu3BTNActionPerformed

    private void Menu5BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu5BTNActionPerformed
        // TODO add your handling code here:
        addToList(Menu5BTN.getText());
    }//GEN-LAST:event_Menu5BTNActionPerformed

    private void Menu2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2BTNActionPerformed
        // TODO add your handling code here:
        addToList(Menu2BTN.getText());
    }//GEN-LAST:event_Menu2BTNActionPerformed

    private void Menu4BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu4BTNActionPerformed
        // TODO add your handling code here:
        addToList(Menu4BTN.getText());
    }//GEN-LAST:event_Menu4BTNActionPerformed

    private void Menu1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1BTNActionPerformed
        // TODO add your handling code here:
        addToList(Menu1BTN.getText());
    }//GEN-LAST:event_Menu1BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame a = new NewJFrame();
                a.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JList<String> CartList;
    private javax.swing.JButton ClearCart;
    private javax.swing.JButton ComboListBTN;
    private javax.swing.JButton DessertListBTN;
    private javax.swing.JButton DrinkListBTN;
    private javax.swing.JButton EntreeListBTN;
    private javax.swing.JButton Menu1BTN;
    private javax.swing.JButton Menu2BTN;
    private javax.swing.JButton Menu3BTN;
    private javax.swing.JButton Menu4BTN;
    private javax.swing.JButton Menu5BTN;
    private javax.swing.JButton Menu6BTN;
    private javax.swing.JButton Menu7BTN;
    private javax.swing.JButton Menu8BTN;
    private javax.swing.JTabbedPane MenuTab;
    private javax.swing.JButton NextPageBTN;
    private javax.swing.JButton PrevPageBTN;
    private javax.swing.JButton SidesListBTN;
    private javax.swing.JButton SubmitOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
